In [1]:
# Interview sentiment

In [1]:
import pandas as pd
import string
import seaborn as sns
import matplotlib.pyplot as plt
import collections
import nltk
from nltk.tokenize import word_tokenize
from nltk.sentiment import SentimentIntensityAnalyzer
from collections import Counter

In [2]:
data = pd.read_csv('interview-b.csv')
print(data.dtypes)
print("--------DataType of DataFrame after converting---------")
df=data.convert_dtypes()
print(df.dtypes)

timecode      object
transcript    object
dtype: object
--------DataType of DataFrame after converting---------
timecode      string[python]
transcript    string[python]
dtype: object

In [3]:
df

,timecode,transcript
0,00:00:00.00 - 00:00:01.42,sounds very official.
1,00:00:01.43 - 00:00:05.02,This session is now being recorded Alright.
2,00:00:05.03 - 00:00:08.19,"Very official, very official."
3,00:00:08.20 - 00:00:25.86,Um Okay so we are working on some research wit...
4,00:00:25.87 - 00:00:36.86,I basically have been talking to a lot of diff...
...,...,...
372,00:43:47.01 - 00:43:51.97,"So um yeah, I'll make sure to share some of th..."
373,00:43:52.17 - 00:43:53.48,Yeah.
374,00:43:53.49 - 00:43:55.52,"Um Well, thank you very much."
375,00:43:55.53 - 00:44:01.44,"This has been super, super helpful and yeah, w..."
376,00:44:01.45 - 00:44:01.74,Great.

In [4]:
nltk.download('vader_lexicon')
#run this cell to see how the sentiment analyzer works
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/karol/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [5]:
#create a new column called polarity and apply the sia method to the clean_lyric column with a lambda expression
df['polarity'] = df['transcript'].apply(lambda x: sia.polarity_scores(x))
df.head()

,timecode,transcript,polarity
0,00:00:00.00 - 00:00:01.42,sounds very official.,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
1,00:00:01.43 - 00:00:05.02,This session is now being recorded Alright.,"{'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compou..."
2,00:00:05.03 - 00:00:08.19,"Very official, very official.","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
3,00:00:08.20 - 00:00:25.86,Um Okay so we are working on some research wit...,"{'neg': 0.0, 'neu': 0.796, 'pos': 0.204, 'comp..."
4,00:00:25.87 - 00:00:36.86,I basically have been talking to a lot of diff...,"{'neg': 0.137, 'neu': 0.591, 'pos': 0.271, 'co..."

In [6]:
#run this cell to transform the polarity dictionary into columns of the DataFrame
df[['neg', 'neu', 'pos', 'compound']] = df['polarity'].apply(pd.Series)
df.drop('polarity', axis=1)

,timecode,transcript,neg,neu,pos,compound
0,00:00:00.00 - 00:00:01.42,sounds very official.,0.000,1.000,0.000,0.0000
1,00:00:01.43 - 00:00:05.02,This session is now being recorded Alright.,0.000,0.750,0.250,0.2500
2,00:00:05.03 - 00:00:08.19,"Very official, very official.",0.000,1.000,0.000,0.0000
3,00:00:08.20 - 00:00:25.86,Um Okay so we are working on some research wit...,0.000,0.796,0.204,0.7096
4,00:00:25.87 - 00:00:36.86,I basically have been talking to a lot of diff...,0.137,0.591,0.271,0.6621
...,...,...,...,...,...,...
372,00:43:47.01 - 00:43:51.97,"So um yeah, I'll make sure to share some of th...",0.000,0.537,0.463,0.8166
373,00:43:52.17 - 00:43:53.48,Yeah.,0.000,0.000,1.000,0.2960
374,00:43:53.49 - 00:43:55.52,"Um Well, thank you very much.",0.000,0.465,0.535,0.5574
375,00:43:55.53 - 00:44:01.44,"This has been super, super helpful and yeah, w...",0.000,0.385,0.615,0.9153
376,00:44:01.45 - 00:44:01.74,Great.,0.000,0.000,1.000,0.6249

In [7]:
#df.sort_values(by='neg', ascending=False)
#df.sort_values(by='pos', ascending=False)
#df.sort_values(by='compound', ascending=False)

In [8]:
df.to_csv('interview_b_sentiment.csv')